# Generated by Django 3.1.4 on 2020-12-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0002_auto_20201205_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='task_description',
            field=models.TextField(blank=True),
        ),
    ]
