# Generated by Django 3.1.4 on 2021-01-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0003_auto_20201205_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='tags',
            field=models.ManyToManyField(to='todoList.Tag'),
        ),
        migrations.DeleteModel(
            name='TaskTags',
        ),
    ]
