# Generated by Django 3.1.4 on 2021-01-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0004_auto_20210102_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_color',
            field=models.CharField(max_length=7),
        ),
    ]
