# Generated by Django 3.1.4 on 2021-01-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0006_todotask_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='created_next',
            field=models.BooleanField(default=False),
        ),
    ]
